In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.impute import KNNImputer

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
print(train_data.shape)
train_data.head()

(8693, 14)


PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [4]:
print(test_data.shape)
test_data.head()

(4277, 13)


PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [5]:
test_data['Transported'] = False
test_data.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  \
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning   
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers   
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus   
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter   
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez   

   Transported  
0        False  
1        False  
2        False  
3        False  
4        False

In [6]:
df = pd.concat([train_data, test_data], axis=0)
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [7]:
df.drop(columns=['PassengerId', 'Name'], inplace=True)
df.head()

HomePlanet CryoSleep  Cabin  Destination   Age    VIP  RoomService  \
0     Europa     False  B/0/P  TRAPPIST-1e  39.0  False          0.0   
1      Earth     False  F/0/S  TRAPPIST-1e  24.0  False        109.0   
2     Europa     False  A/0/S  TRAPPIST-1e  58.0   True         43.0   
3     Europa     False  A/0/S  TRAPPIST-1e  33.0  False          0.0   
4      Earth     False  F/1/S  TRAPPIST-1e  16.0  False        303.0   

   FoodCourt  ShoppingMall     Spa  VRDeck  Transported  
0        0.0           0.0     0.0     0.0        False  
1        9.0          25.0   549.0    44.0         True  
2     3576.0           0.0  6715.0    49.0        False  
3     1283.0         371.0  3329.0   193.0        False  
4       70.0         151.0   565.0     2.0         True

In [8]:
df[['Deck', 'Num', 'Side']] = df['Cabin'].str.split('/', expand = True) # if expand False the will split and put the results in a list
df.head()

HomePlanet CryoSleep  Cabin  Destination   Age    VIP  RoomService  \
0     Europa     False  B/0/P  TRAPPIST-1e  39.0  False          0.0   
1      Earth     False  F/0/S  TRAPPIST-1e  24.0  False        109.0   
2     Europa     False  A/0/S  TRAPPIST-1e  58.0   True         43.0   
3     Europa     False  A/0/S  TRAPPIST-1e  33.0  False          0.0   
4      Earth     False  F/1/S  TRAPPIST-1e  16.0  False        303.0   

   FoodCourt  ShoppingMall     Spa  VRDeck  Transported Deck Num Side  
0        0.0           0.0     0.0     0.0        False    B   0    P  
1        9.0          25.0   549.0    44.0         True    F   0    S  
2     3576.0           0.0  6715.0    49.0        False    A   0    S  
3     1283.0         371.0  3329.0   193.0        False    A   0    S  
4       70.0         151.0   565.0     2.0         True    F   1    S

In [9]:
df.drop(['Cabin'],axis=1, inplace=True)
df.head()

HomePlanet CryoSleep  Destination   Age    VIP  RoomService  FoodCourt  \
0     Europa     False  TRAPPIST-1e  39.0  False          0.0        0.0   
1      Earth     False  TRAPPIST-1e  24.0  False        109.0        9.0   
2     Europa     False  TRAPPIST-1e  58.0   True         43.0     3576.0   
3     Europa     False  TRAPPIST-1e  33.0  False          0.0     1283.0   
4      Earth     False  TRAPPIST-1e  16.0  False        303.0       70.0   

   ShoppingMall     Spa  VRDeck  Transported Deck Num Side  
0           0.0     0.0     0.0        False    B   0    P  
1          25.0   549.0    44.0         True    F   0    S  
2           0.0  6715.0    49.0        False    A   0    S  
3         371.0  3329.0   193.0        False    A   0    S  
4         151.0   565.0     2.0         True    F   1    S

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12682 non-null  object 
 1   CryoSleep     12660 non-null  object 
 2   Destination   12696 non-null  object 
 3   Age           12700 non-null  float64
 4   VIP           12674 non-null  object 
 5   RoomService   12707 non-null  float64
 6   FoodCourt     12681 non-null  float64
 7   ShoppingMall  12664 non-null  float64
 8   Spa           12686 non-null  float64
 9   VRDeck        12702 non-null  float64
 10  Transported   12970 non-null  bool   
 11  Deck          12671 non-null  object 
 12  Num           12671 non-null  object 
 13  Side          12671 non-null  object 
dtypes: bool(1), float64(6), object(7)
memory usage: 1.4+ MB


In [11]:
df['Num'].unique()

array(['0', '1', '2', ..., '1885', '1887', '1890'], dtype=object)

In [12]:
df['VIP'] = df['VIP'].astype(bool)
df['CryoSleep'] = df['CryoSleep'].astype(bool)
df['Num'] = df['Num'].astype(float)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12682 non-null  object 
 1   CryoSleep     12970 non-null  bool   
 2   Destination   12696 non-null  object 
 3   Age           12700 non-null  float64
 4   VIP           12970 non-null  bool   
 5   RoomService   12707 non-null  float64
 6   FoodCourt     12681 non-null  float64
 7   ShoppingMall  12664 non-null  float64
 8   Spa           12686 non-null  float64
 9   VRDeck        12702 non-null  float64
 10  Transported   12970 non-null  bool   
 11  Deck          12671 non-null  object 
 12  Num           12671 non-null  float64
 13  Side          12671 non-null  object 
dtypes: bool(3), float64(7), object(4)
memory usage: 1.2+ MB


In [14]:
object_columns = [col for col in df.columns if df[col].dtype == 'object']
numeric_columns = [col for col in df.columns if df[col].dtype != 'object']

In [15]:
object_columns, numeric_columns

(['HomePlanet', 'Destination', 'Deck', 'Side'],
 ['CryoSleep',
  'Age',
  'VIP',
  'RoomService',
  'FoodCourt',
  'ShoppingMall',
  'Spa',
  'VRDeck',
  'Transported',
  'Num'])

In [16]:
df.isna().sum()[df.dtypes=='object'].sort_values(ascending=False)

Deck           299
Side           299
HomePlanet     288
Destination    274
dtype: int64

In [17]:
for col in object_columns:
    df[col] = df[col].fillna('N')

In [18]:
df.isna().sum()[df.dtypes=='object'].sort_values(ascending=False)

HomePlanet     0
Destination    0
Deck           0
Side           0
dtype: int64

In [19]:
for col in object_columns:
    df = pd.concat([df, pd.get_dummies(df[col])], axis=1)

In [20]:
df.drop(columns=object_columns, inplace=True)
df.head()

CryoSleep   Age    VIP  RoomService  FoodCourt  ShoppingMall     Spa  \
0      False  39.0  False          0.0        0.0           0.0     0.0   
1      False  24.0  False        109.0        9.0          25.0   549.0   
2      False  58.0   True         43.0     3576.0           0.0  6715.0   
3      False  33.0  False          0.0     1283.0         371.0  3329.0   
4      False  16.0  False        303.0       70.0         151.0   565.0   

   VRDeck  Transported  Num  ...      C      D      E      F      G      N  \
0     0.0        False  0.0  ...  False  False  False  False  False  False   
1    44.0         True  0.0  ...  False  False  False   True  False  False   
2    49.0        False  0.0  ...  False  False  False  False  False  False   
3   193.0        False  0.0  ...  False  False  False  False  False  False   
4     2.0         True  1.0  ...  False  False  False   True  False  False   

       T      N      P      S  
0  False  False   True  False  
1  False  False  False   True  
2  False  False  False   True  
3  False  False  False   True  
4  False  False  False   True  

[5 rows x 30 columns]

In [21]:
df.isna().sum()[df.dtypes != 'object'].sort_values(ascending=False)

ShoppingMall     306
Num              299
FoodCourt        289
Spa              284
Age              270
VRDeck           268
RoomService      263
G                  0
D                  0
E                  0
F                  0
CryoSleep          0
N                  0
T                  0
B                  0
N                  0
P                  0
C                  0
N                  0
A                  0
TRAPPIST-1e        0
PSO J318.5-22      0
55 Cancri e        0
N                  0
Mars               0
Europa             0
Earth              0
Transported        0
VIP                0
S                  0
dtype: int64

In [22]:
imputer = KNNImputer(n_neighbors=5)
imputed_data = imputer.fit_transform(df)
df = pd.DataFrame(imputed_data, columns=df.columns)
df.head()

CryoSleep   Age  VIP  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0        0.0  39.0  0.0          0.0        0.0           0.0     0.0     0.0   
1        0.0  24.0  0.0        109.0        9.0          25.0   549.0    44.0   
2        0.0  58.0  1.0         43.0     3576.0           0.0  6715.0    49.0   
3        0.0  33.0  0.0          0.0     1283.0         371.0  3329.0   193.0   
4        0.0  16.0  0.0        303.0       70.0         151.0   565.0     2.0   

   Transported  Num  ...    C    D    E    F    G    N    T    N    P    S  
0          0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1          1.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  
2          0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
3          0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4          1.0  1.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  

[5 rows x 30 columns]

In [23]:
df.isna().sum()

CryoSleep        0
Age              0
VIP              0
RoomService      0
FoodCourt        0
ShoppingMall     0
Spa              0
VRDeck           0
Transported      0
Num              0
Earth            0
Europa           0
Mars             0
N                0
55 Cancri e      0
N                0
PSO J318.5-22    0
TRAPPIST-1e      0
A                0
B                0
C                0
D                0
E                0
F                0
G                0
N                0
T                0
N                0
P                0
S                0
dtype: int64

In [24]:
bill_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
df['amt_spent'] = df[bill_cols].sum(axis = 1)
df['std_amt_spent'] = df[bill_cols].std(axis = 1)
df['mean_amt_spent'] = df[bill_cols].mean(axis = 1)

In [25]:
df.corr()['Transported'].sort_values(ascending = False)

Transported       1.000000
CryoSleep         0.315576
Europa            0.131977
B                 0.107559
55 Cancri e       0.083625
C                 0.079540
S                 0.073741
FoodCourt         0.034923
G                 0.016048
A                 0.007513
N                 0.006403
Mars              0.005643
ShoppingMall      0.003857
PSO J318.5-22     0.000760
N                -0.000554
N                -0.001007
N                -0.001007
VIP              -0.009605
T                -0.015196
D                -0.025659
Num              -0.038872
Age              -0.049929
F                -0.070171
E                -0.071961
TRAPPIST-1e      -0.072731
P                -0.073463
Earth            -0.119644
std_amt_spent    -0.121486
amt_spent        -0.140667
mean_amt_spent   -0.140667
VRDeck           -0.142913
Spa              -0.155162
RoomService      -0.174852
Name: Transported, dtype: float64

In [26]:
train, test = df[:len(train_data)], df[len(train_data):]
train.shape, test.shape

((8693, 33), (4277, 33))

In [27]:
test.drop(columns=['Transported'], inplace=True)
test.shape

<ipython-input-27-49c21378f21e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop(columns=['Transported'], inplace=True)


(4277, 32)

In [28]:
X = train.drop(['Transported'], axis=1)
y = train['Transported']

In [29]:
y.value_counts()

Transported
1.0    4378
0.0    4315
Name: count, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6954, 32), (1739, 32), (6954,), (1739,))

In [31]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)


In [33]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.80      0.73      0.76       861
         1.0       0.76      0.82      0.79       878

    accuracy                           0.78      1739
   macro avg       0.78      0.78      0.78      1739
weighted avg       0.78      0.78      0.78      1739

[[632 229]
 [161 717]]
0.7757331799884991


In [34]:
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.79      0.80      0.79       861
         1.0       0.80      0.79      0.80       878

    accuracy                           0.79      1739
   macro avg       0.79      0.79      0.79      1739
weighted avg       0.79      0.79      0.79      1739

[[689 172]
 [185 693]]
0.7947096032202415


In [35]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.74      0.73      0.73       861
         1.0       0.74      0.75      0.74       878

    accuracy                           0.74      1739
   macro avg       0.74      0.74      0.74      1739
weighted avg       0.74      0.74      0.74      1739

[[626 235]
 [222 656]]
0.7372052903967797


In [43]:
rf = RandomForestClassifier(max_depth=None, n_estimators=1000)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.78      0.81      0.79       861
         1.0       0.81      0.77      0.79       878

    accuracy                           0.79      1739
   macro avg       0.79      0.79      0.79      1739
weighted avg       0.79      0.79      0.79      1739

[[697 164]
 [200 678]]
0.7906843013225991


In [37]:
lgbm = LGBMClassifier()
lgbm.fit(X_train, y_train)
y_pred = lgbm.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


[LightGBM] [Info] Number of positive: 3500, number of negative: 3454
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007728 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 6954, number of used features: 31
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.503307 -> initscore=0.013230
[LightGBM] [Info] Start training from score 0.013230
              precision    recall  f1-score   support

         0.0       0.80      0.79      0.79       861
         1.0       0.80      0.80      0.80       878

    accuracy                           0.80      1739
   macro avg       0.80      0.80      0.80      1739
weighted avg       0.80      0.80      0.80      1739

[[682 179]
 [175 703]]
0.7964347326049454


/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [44]:
df_dummy = pd.read_csv('test.csv')
pred = lgbm.predict(test)

final = pd.DataFrame()
final['PassengerId'] = df_dummy['PassengerId']
final['Transported'] = pred

final.to_csv('submission.csv', index = False)